### ISSUE TITLE
Nuki Adapter 1.0.4 failed to start

### ISSUE THREAD

**Issue by flydus** [Zefau/ioBroker.nuki2#23]
Since the update to Version 1.0.4 the adapter failed to start.

Here is my Log:

2019-09-18 10:02:22.061  - [32minfo[39m: host.buanet-iobroker1 instance system.adapter.nuki2.0 started with pid 22813
2019-09-18 10:02:23.289  - [31merror[39m: Caught by controller[0]: /opt/iobroker/node_modules/iobroker.nuki2/lib/library.js:485
2019-09-18 10:02:23.289  - [31merror[39m: Caught by controller[0]: 	async _setValue(state, value)
2019-09-18 10:02:23.289  - [31merror[39m: Caught by controller[0]: 	      ^^^^^^^^^
2019-09-18 10:02:23.289  - [31merror[39m: Caught by controller[0]: SyntaxError: Unexpected identifier
2019-09-18 10:02:23.289  - [31merror[39m: Caught by controller[0]:     at createScript (vm.js:56:10)
2019-09-18 10:02:23.289  - [31merror[39m: Caught by controller[0]:     at Object.runInThisContext (vm.js:97:10)
2019-09-18 10:02:23.290  - [31merror[39m: Caught by controller[0]:     at Module._compile (module.js:549:28)
2019-09-18 10:02:23.290  - [31merror[39m: Caught by controller[0]:     at Object.Module._extensions..js (module.js:586:10)
2019-09-18 10:02:23.290  - [31merror[39m: Caught by controller[0]:     at Module.load (module.js:494:32)
2019-09-18 10:02:23.290  - [31merror[39m: Caught by controller[0]:     at tryModuleLoad (module.js:453:12)
2019-09-18 10:02:23.290  - [31merror[39m: Caught by controller[0]:     at Function.Module._load (module.js:445:3)
2019-09-18 10:02:23.290  - [31merror[39m: Caught by controller[0]:     at Module.require (module.js:504:17)
2019-09-18 10:02:23.290  - [31merror[39m: Caught by controller[0]:     at require (internal/module.js:20:19)
2019-09-18 10:02:23.290  - [31merror[39m: Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.nuki2/nuki2.js:18:17)
2019-09-18 10:02:23.290  - [31merror[39m: Caught by controller[0]:     at Module._compile (module.js:577:32)
2019-09-18 10:02:23.290  - [31merror[39m: Caught by controller[0]:     at Object.Module._extensions..js (module.js:586:10)
2019-09-18 10:02:23.290  - [31merror[39m: Caught by controller[0]:     at Module.load (module.js:494:32)
2019-09-18 10:02:23.290  - [31merror[39m: Caught by controller[0]:     at tryModuleLoad (module.js:453:12)
2019-09-18 10:02:23.291  - [31merror[39m: Caught by controller[0]:     at Function.Module._load (module.js:445:3)
2019-09-18 10:02:23.291  - [31merror[39m: Caught by controller[0]:     at Module.runMain (module.js:611:10)
2019-09-18 10:02:23.291  - [31merror[39m: Caught by controller[0]:     at run (bootstrap_node.js:394:7)
2019-09-18 10:02:23.291  - [31merror[39m: Caught by controller[0]:     at startup (bootstrap_node.js:160:9)
2019-09-18 10:02:23.291  - [31merror[39m: Caught by controller[0]:     at bootstrap_node.js:507:3
2019-09-18 10:02:23.291  - [31merror[39m: host.buanet-iobroker1 instance system.adapter.nuki2.0 terminated with code 1 ()
2019-09-18 10:02:23.291  - [32minfo[39m: host.buanet-iobroker1 Restart adapter system.adapter.nuki2.0 because enabled

**Comment by Zefau** [comment]
Looks like your Node.js version is too old. Which version are you on?

**Comment by flydus** [comment]
Hi Zefau,

thanks for quick reply....

My Node.js version is v6.17.1

**Comment by Zefau** [comment]
Node.js v6 is not supported unfortunately, because (as the error states) the functionality of `async` / `await` is not included in v6.
I will add a warning / notice in a future version of the adapter.
